### PR TITLE
fix: filter queried elements inside template element

### PR DESCRIPTION
**Pull request by andolf**
This should hopefully solve the bug that exists over here:
https://github.com/cheeriojs/cheerio/issues/2643

### CODE REVIEW

**Comment by fb55** [comment]
Hi @andolf, I don't think this will do what you hope it will do; the `options.adapter.findAll` call will still traverse into `<template>` child elements. The best way around this is probably to hand-roll `findAll` inside of `css-select` using the existing adapter methods (see https://github.com/fb55/domutils/blob/bf4aeeff4f3ce1072ecafb78ecc3427c7ff15496/src/querying.ts#L125-L150 for the current implementation), and prevent traversals _into_ `<template>` tags.

**Comment by andolf** [comment]
Thanks @fb55. I suspected that was the right approach, but was looking for some guidance.
I'll take another stab at this today and see if I can get something together for next week.

**Comment by andolf** [comment]
Any new input on this one? @fb55

**Comment by fb55** [comment]
Sorry, missed that you pushed changes. I see two remaining issues:

1. Please don't expand the qwery test suite, as that was taken from the qwery project and shouldn't be changed. Feel free to add a new spec, or add to one of the suites not adapted from another library (sizzle, nwmatcher, or qwery).
2. The change currently does not respect xml mode. In xml mode, template elements shouldn't have any custom behavior.

**Comment by fb55** [comment]
Thanks a lot @andolf! I've followed up with some changes in #1001.

**Pull request merged**
